/**
  A database schema for 'FURNITURE SHOP' web application.
 */
CREATE SCHEMA furniture_shop;
/**
   Creating tables script for 'FURNITURE SHOP' web application.
 */

/*
  A table with visitor's roles.
 */
CREATE TABLE furniture_shop.ROLE(
  ROLE_ID BIGSERIAL PRIMARY KEY,
  TITLE VARCHAR(20) NOT NULL,
  CHECK (TITLE IN ('ROLE_ADMIN', 'ROLE_MANAGER', 'ROLE_USER'))
);

/**
  A table with customers' delivery requisites
 */
CREATE TABLE furniture_shop.REQUISITE
(
  REQUISITE_ID BIGSERIAL PRIMARY KEY,
  ZIP VARCHAR(10),
  COUNTRY VARCHAR(50),
  CITY VARCHAR(50),
  ADDRESS VARCHAR(50)
);

/**
  A table with customers' registration data.
 */
CREATE TABLE furniture_shop.USERS
(
  USER_ID BIGSERIAL PRIMARY KEY,
  FULLNAME VARCHAR(100) NOT NULL,
  LOGIN VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  REQUISITE_ID BIGINT,
  BIRTHDAY DATE,
  SEX BOOLEAN,
  TEAM INT,

  FOREIGN KEY (ROLE_ID) REFERENCES furniture_shop.ROLE(ROLE_ID),
  FOREIGN KEY (REQUISITE_ID) REFERENCES furniture_shop.REQUISITE(REQUISITE_ID)
);


/**
  A table that represents manufacturers of products
 */
CREATE TABLE furniture_shop.MANUFACTURER
(
  MANUFACTURER_ID BIGSERIAL PRIMARY KEY ,
  REQUISITE_ID BIGINT,
  TITLE VARCHAR(100) NOT NULL ,

  FOREIGN KEY (REQUISITE_ID) REFERENCES furniture_shop.REQUISITE(REQUISITE_ID)
);

/**
  A table that represents categories of products
 */
CREATE TABLE furniture_shop.CATEGORY
(
  CATEGORY_ID BIGSERIAL PRIMARY KEY ,
  TITLE VARCHAR(50) NOT NULL
);

/**
  A table of furniture shop products
 */
CREATE TABLE furniture_shop.PRODUCT
(
  PRODUCT_ID BIGSERIAL PRIMARY KEY ,
  MANUFACTURER_ID BIGINT NOT NULL ,
  MANAGER_ID BIGINT NOT NULL ,
  CATEGORY_ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL ,
  DESCRIPTION VARCHAR ,

  FOREIGN KEY (MANUFACTURER_ID) REFERENCES furniture_shop.MANUFACTURER (MANUFACTURER_ID),
  FOREIGN KEY (CATEGORY_ID) REFERENCES furniture_shop.CATEGORY (CATEGORY_ID),
  FOREIGN KEY (MANAGER_ID) REFERENCES furniture_shop.USERS(USER_ID)
);

/**
  A table with images of products
 */
CREATE TABLE furniture_shop.PRODUCT_IMAGE
(
  PRODUCT_IMAGE_ID BIGSERIAL PRIMARY KEY ,
  PRODUCT_ID BIGINT NOT NULL ,
  URL VARCHAR(500) NOT NULL ,

  FOREIGN KEY (PRODUCT_ID) REFERENCES furniture_shop.PRODUCT(PRODUCT_ID)
);

/**
  A table that stores sailing info about product (code, price, quantity)
 */
CREATE TABLE furniture_shop.STORAGE
(
  STORAGE_ID BIGSERIAL PRIMARY KEY ,
  PRODUCT_ID BIGINT NOT NULL ,
  CODE VARCHAR(10) UNIQUE NOT NULL ,
  PRICE NUMERIC(8,2) DEFAULT 0.00,
  QUANTITY SMALLINT DEFAULT 0,

  FOREIGN KEY (PRODUCT_ID) REFERENCES furniture_shop.PRODUCT(PRODUCT_ID)
);

/**
  A table that represents customers' orders
 */
CREATE TABLE furniture_shop.ORDERS
(
  ORDER_ID BIGSERIAL PRIMARY KEY ,
  CUSTOMER_ID BIGINT NOT NULL ,
  MANAGER_ID BIGINT NOT NULL ,
  CREATE_DATE TIMESTAMP,
  FINISH_DATE TIMESTAMP,

  FOREIGN KEY (CUSTOMER_ID) REFERENCES furniture_shop.USERS(USER_ID),
  FOREIGN KEY (MANAGER_ID) REFERENCES furniture_shop.USERS(USER_ID)
);

/**
  A table with order details (products and their quantity)
 */
CREATE TABLE furniture_shop.ORDER_DETAILS
(
  ORDER_DETAILS_ID BIGSERIAL PRIMARY KEY ,
  ORDER_ID BIGINT NOT NULL ,
  PRODUCT_ID BIGINT NOT NULL ,
  QUANTITY SMALLINT DEFAULT 1,

  FOREIGN KEY (ORDER_ID) REFERENCES furniture_shop.ORDERS(ORDER_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES furniture_shop.PRODUCT(PRODUCT_ID)
);

/**
  A temporary table of products that the user placed in basket.
 */
CREATE TABLE furniture_shop.BASKET
(
  BASKET_ID BIGSERIAL PRIMARY KEY ,
  CUSTOMER_ID BIGINT NOT NULL ,
  PRODUCT_ID BIGINT NOT NULL,
  QUANTITY SMALLINT DEFAULT 1,

  FOREIGN KEY (CUSTOMER_ID) REFERENCES furniture_shop.USERS(user_id)
);