/**
  A database schema for 'FURNITURE SHOP' web application.
 */
CREATE SCHEMA furniture_shop;
/**
   Creating tables script for 'FURNITURE SHOP' web application.
 */

/*
  A table with visitor's roles.
 */
CREATE TABLE furniture_shop.ROLE(
  ROLE_ID BIGSERIAL PRIMARY KEY,
  TITLE VARCHAR(20) NOT NULL,
  CHECK (TITLE IN ('ROLE_ADMIN', 'ROLE_MANAGER', 'ROLE_USER'))
);

/**
  A table with customers' registration data.
 */
CREATE TABLE furniture_shop.CUSTOMER
(
  CUSTOMER_ID BIGSERIAL PRIMARY KEY,
  FULLNAME VARCHAR(100) NOT NULL,
  LOGIN VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ROLE_ID BIGINT NOT NULL,
  BIRTHDAY TIMESTAMP,
  SEX BOOLEAN,

  FOREIGN KEY (ROLE_ID) REFERENCES furniture_shop.ROLE(ROLE_ID)
);

/**
  A table with customers' delivery requisites
 */
CREATE TABLE furniture_shop.DELIVERY_REQUISITE
(
  DELIVERY_REQUISITE_ID BIGSERIAL PRIMARY KEY,
  ZIP VARCHAR(10) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL ,
  CITY VARCHAR(50) NOT NULL ,
  ADDRESS VARCHAR(50) NOT NULL
);

/**
  A table that binds customers and theirs delivery requisites
 */
CREATE TABLE furniture_shop.CUSTOMER_DELIVERY_REQUISITE
(
  CUSTOMER_ID BIGINT NOT NULL ,
  DELIVERY_REQUISITE_ID BIGINT NOT NULL,

  PRIMARY KEY (CUSTOMER_ID, DELIVERY_REQUISITE_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES furniture_shop.CUSTOMER(CUSTOMER_ID),
  FOREIGN KEY (DELIVERY_REQUISITE_ID) REFERENCES furniture_shop.DELIVERY_REQUISITE(DELIVERY_REQUISITE_ID)

);

/**
  A table that represents manufacturers of products
 */
CREATE TABLE furniture_shop.MANUFACTURER
(
  MANUFACTURER_ID BIGSERIAL PRIMARY KEY ,
  DELIVERY_REQUISITE_ID BIGINT NOT NULL ,
  TITLE VARCHAR(100) NOT NULL ,

  FOREIGN KEY (DELIVERY_REQUISITE_ID) REFERENCES furniture_shop.DELIVERY_REQUISITE(DELIVERY_REQUISITE_ID)
);

/**
  A table that represents categories of products
 */
CREATE TABLE furniture_shop.CATEGORY
(
  CATEGORY_ID BIGSERIAL PRIMARY KEY ,
  TITLE VARCHAR(50) NOT NULL
);

/**
  A table of furniture shop products
 */
CREATE TABLE furniture_shop.PRODUCT
(
  PRODUCT_ID BIGSERIAL PRIMARY KEY ,
  MANUFACTURER_ID BIGINT NOT NULL ,
  CATEGORY_ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL ,
  DESCRIPTION VARCHAR ,

  FOREIGN KEY (MANUFACTURER_ID) REFERENCES furniture_shop.MANUFACTURER (MANUFACTURER_ID),
  FOREIGN KEY (CATEGORY_ID) REFERENCES furniture_shop.CATEGORY (CATEGORY_ID)
);

/**
  A table with images of products
 */
CREATE TABLE furniture_shop.PRODUCT_IMAGE
(
  PRODUCT_IMAGE_ID BIGSERIAL PRIMARY KEY ,
  PRODUCT_ID BIGINT NOT NULL ,
  URL VARCHAR(500) NOT NULL ,

  FOREIGN KEY (PRODUCT_ID) REFERENCES furniture_shop.PRODUCT(PRODUCT_ID)
);

/**
  A table that stores sailing info about product (code, price, quantity)
 */
CREATE TABLE furniture_shop.STORAGE
(
  STORAGE_ID BIGSERIAL PRIMARY KEY ,
  PRODUCT_ID BIGINT NOT NULL ,
  CODE VARCHAR(10) UNIQUE NOT NULL ,
  PRICE NUMERIC(8,2) DEFAULT 0.00,
  QUANTITY SMALLINT DEFAULT 0,

  FOREIGN KEY (PRODUCT_ID) REFERENCES furniture_shop.PRODUCT(PRODUCT_ID)
);

/**
  A table that represents customers' orders
 */
CREATE TABLE furniture_shop.ORDERS
(
  ORDER_ID BIGSERIAL PRIMARY KEY ,
  CUSTOMER_ID BIGINT NOT NULL ,
  CREATE_DATE TIMESTAMP,
  FINISH_DATE TIMESTAMP,

  FOREIGN KEY (CUSTOMER_ID) REFERENCES furniture_shop.CUSTOMER(CUSTOMER_ID)
);

/**
  A table with order details (products and their quantity)
 */
CREATE TABLE furniture_shop.ORDER_DETAILS
(
  ORDER_ID BIGINT NOT NULL ,
  CUSTOMER_ID BIGINT NOT NULL ,
  PRODUCT_ID BIGINT NOT NULL ,
  QUANTITY SMALLINT DEFAULT 1,

  PRIMARY KEY (ORDER_ID, CUSTOMER_ID, PRODUCT_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES furniture_shop.ORDERS(ORDER_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES furniture_shop.CUSTOMER(CUSTOMER_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES furniture_shop.PRODUCT(PRODUCT_ID)
);

/**
  A temporary table of products that the customer placed in basket.
 */
CREATE TEMP TABLE BASKET
(
  PRODUCT_ID BIGINT NOT NULL,
  QUANTITY SMALLINT DEFAULT 1
);