/**
   Creating tables script for 'FURNITURE SHOP' web application.
 */

/*
  A table with visitor's roles.
 */
CREATE TABLE ROLE(
  ROLE_ID SMALLSERIAL PRIMARY KEY,
  TITLE VARCHAR(10) NOT NULL,
  CHECK (TITLE IN ('ROLE_ADMIN', 'ROLE_USER', 'ROLE_GUEST'))
);

/**
  A table with customers' registration data.
 */
CREATE TABLE CUSTOMER
(
  CUSTOMER_ID SERIAL PRIMARY KEY,
  FULLNAME VARCHAR(100) NOT NULL,
  LOGIN VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ROLE_ID SMALLINT NOT NULL,

  FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);

/**
  A table with customers' delivery requisites
 */
CREATE TABLE DELIVERY_REQUISITE
(
  DELIVERY_REQUISITE_ID SERIAL PRIMARY KEY,
  ZIP VARCHAR(10) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL ,
  CITY VARCHAR(50) NOT NULL ,
  ADDRESS VARCHAR(50) NOT NULL
);

/**
  A table that binds customers and theirs delivery requisites
 */
CREATE TABLE CUSTOMER_DELIVERY_REQUISITE
(
  CUSTOMER_ID INTEGER NOT NULL ,
  DELIVERY_REQUISITE_ID INTEGER NOT NULL,

  PRIMARY KEY (CUSTOMER_ID, DELIVERY_REQUISITE_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
  FOREIGN KEY (DELIVERY_REQUISITE_ID) REFERENCES DELIVERY_REQUISITE(DELIVERY_REQUISITE_ID)

);

/**
  A table that represents manufacturers of products
 */
CREATE TABLE MANUFACTURER
(
  MANUFACTURER_ID SMALLSERIAL PRIMARY KEY ,
  DELIVERY_REQUISITE_ID INTEGER NOT NULL ,
  TITLE VARCHAR(100) NOT NULL ,

  FOREIGN KEY (DELIVERY_REQUISITE_ID) REFERENCES DELIVERY_REQUISITE(DELIVERY_REQUISITE_ID)
);

/**
  A table that represents categories of products
 */
CREATE TABLE CATEGORY
(
  CATEGORY_ID SMALLSERIAL PRIMARY KEY ,
  TITLE VARCHAR(50) NOT NULL
);

/**
  A table of furniture shop products
 */
CREATE TABLE PRODUCT
(
  PRODUCT_ID SERIAL PRIMARY KEY ,
  MANUFACTURER_ID SMALLINT NOT NULL ,
  CATEGORY_ID SMALLINT NOT NULL,
  NAME VARCHAR(50) NOT NULL ,
  DESCRIPTION TEXT ,

  FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER (MANUFACTURER_ID),
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID)
);

/**
  A table with images of products
 */
CREATE TABLE PRODUCT_IMAGE
(
  PRODUCT_IMAGE_ID SERIAL PRIMARY KEY ,
  PRODUCT_ID INTEGER NOT NULL ,
  URL VARCHAR(500) NOT NULL ,

  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

/**
  A table that stores sailing info about product (code, price, quantity)
 */
CREATE TABLE STORAGE
(
  STORAGE_ID SERIAL PRIMARY KEY ,
  PRODUCT_ID INTEGER NOT NULL ,
  CODE VARCHAR(10) UNIQUE NOT NULL ,
  PRICE MONEY DEFAULT 0.00,
  QUANTITY SMALLINT DEFAULT 0,

  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

/**
  A table that represents customers' orders
 */
CREATE TABLE ORDERS
(
  ORDER_ID SERIAL PRIMARY KEY ,
  CUSTOMER_ID INTEGER NOT NULL ,
  CREATE_DATE TIMESTAMP,
  FINISH_DATE TIMESTAMP,

  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

/**
  A table with order details (products and their quantity)
 */
CREATE TABLE ORDER_DETAILS
(
  ORDER_ID INTEGER NOT NULL ,
  CUSTOMER_ID INTEGER NOT NULL ,
  PRODUCT_ID INTEGER NOT NULL ,
  QUANTITY SMALLINT DEFAULT 1,

  PRIMARY KEY (ORDER_ID, CUSTOMER_ID, PRODUCT_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

/**
  A temporary table of products that the customer placed in basket.
 */
CREATE TEMP TABLE BASKET
(
  PRODUCT_ID INTEGER NOT NULL PRIMARY KEY ,
  QUANTITY SMALLINT DEFAULT 1
);